-- 1.Top-Selling Products by Category
SELECT p.Category, p.SKU, p.Style, SUM(o.Qty) AS TotalQuantitySold
FROM Orders o
JOIN Products p ON o.SKU = p.SKU
GROUP BY p.Category, p.SKU, p.Style
ORDER BY TotalQuantitySold DESC;

--Highest-Selling Product by Category
WITH RankedProducts AS (
    SELECT 
        p.Category, 
        p.SKU, 
        p.Style, 
        SUM(o.Qty) AS TotalQuantitySold,
        ROW_NUMBER() OVER (PARTITION BY p.Category ORDER BY SUM(o.Qty) DESC) AS Rank
    FROM Orders o
    JOIN Products p ON o.SKU = p.SKU
    GROUP BY p.Category, p.SKU, p.Style
)
SELECT 
    Category, 
    SKU, 
    Style, 
    TotalQuantitySold
FROM RankedProducts
WHERE Rank = 1
ORDER BY TotalQuantitySold DESC;

--2.Total Revenue Generated by Each Promotion
SELECT pr.PromotionDetails, SUM(o.Amount) AS TotalRevenue
FROM Orders o
JOIN Promotions pr ON o.PromotionID = pr.PromotionID
GROUP BY pr.PromotionDetails
ORDER BY totalrevenue DESC;

--3.Number of Orders Placed by Each Customer
SELECT c.CustomerID, COUNT(o.OrderID) AS TotalOrders
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID
ORDER BY TotalOrders DESC;

--4.How does sales channel affect order volume and revenue
SELECT 
    SalesChannel,
    COUNT(OrderID) AS OrderVolume,
    SUM(Amount) AS TotalRevenue,
    SUM(Amount) / COUNT(OrderID) AS AverageOrderValue
FROM Orders
GROUP BY SalesChannel
ORDER BY TotalRevenue DESC;

--5.Can we identify any seasonal trends in sales?
SELECT 
    EXTRACT(MONTH FROM Date) AS Month,
    COUNT(OrderID) AS TotalOrders,
    SUM(Amount) AS TotalRevenue
FROM Orders
GROUP BY EXTRACT(MONTH FROM Date)
ORDER BY Month;

--6.What shipService is favoured by Customers
SELECT 
    fo.ShipServiceLevel,
    COUNT(o.OrderID) AS TotalOrders
FROM FulfillmentOptions fo
JOIN Orders o ON fo.FulfillmentID = o.FulfillmentID
GROUP BY fo.ShipServiceLevel
ORDER BY TotalOrders DESC;
